apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: example-lightgbm-mushroom
spec:
  modelType:
    name: lightgbm
  path: lightgbm/mushroom.bst
  storage:
    s3:
      secretKey: localMinIO
