apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: example-sklearn-mnist-svm
spec:
  modelType:
    name: sklearn
  path: sklearn/mnist-svm.joblib
  storage:
    s3:
      secretKey: localMinIO
