apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: example-xgboost-mushroom
spec:
  modelType:
    name: xgboost
  path: xgboost/mushroom.json
  storage:
    s3:
      secretKey: localMinIO
